#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".
git log --pretty=format:'static char* m_acGitHash="Git:%H\n";' -n 1 >./GitHash.h 
: Nothing
