/* Verilog module instantiation template generated by SCUBA Diamond_2.0_Production (151) */
/* Module Version: 5.4 */
/* Tue Aug 23 16:30:45 2016 */

/* parameterized module instance */
fifo64x8 __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ), .AlmostEmpty( ), 
    .AlmostFull( ));
